### PR TITLE
extend github workflows

### PR DESCRIPTION
**Pull request by aminalaee**
- Update scripts
- Update test workflows

### CODE REVIEW

**Comment by aminalaee** [comment]
@tomchristie Will you review this? I think this repo has different permissions compared to the others in `encode`.

**Comment by lovelydinosaur** [comment]
I think we either want to add this repo to the set of repos that are managed by the `encode/maintainers` team, *or* that we need to archive this repo. But I'm not sure which of those two we ought to go for?

**Comment by aminalaee** [comment]
@tomchristie I personally can help with maintaining this as it's related to `databases` and `orm`. I think this can be a nice fit to the rest of the repos.

**Comment by lovelydinosaur** [comment]
Already, added it in. Same perms as the others now. 👍

**Comment by aminalaee** [comment]
@tomchristie I think `maintainers` team has `read` acccess to this repo instead of `maintain`.

**Comment by lovelydinosaur** [comment]
Ooops yup - resolved -thanks!

**Pull request merged**
